//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI_V_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aperturas_Cajas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aperturas_Cajas()
        {
            this.Cierre_Caja = new HashSet<Cierre_Caja>();
        }
    
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public int id_usuario { get; set; }
        public double monto_inicial { get; set; }
        public bool cerrada { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cierre_Caja> Cierre_Caja { get; set; }
    }
}
