//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI_V_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cierre_Caja
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public int id_usuario { get; set; }
        public double total_vendido { get; set; }
        public double total_anulado { get; set; }
        public double entrada_caja { get; set; }
        public double salida_caja { get; set; }
        public double total_caja { get; set; }
        public int id_apertura_caja { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        public virtual Aperturas_Cajas Aperturas_Cajas { get; set; }
    }
}
