//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI_V_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalles_Ordenes
    {
        public int id { get; set; }
        public int orden_id { get; set; }
        public int id_producto { get; set; }
        public int cantidad_producto { get; set; }
        public double precio_producto { get; set; }
        public double itbis { get; set; }
    
        public virtual Ordenes_Reservadas Ordenes_Reservadas { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
