//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI_V_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facturas()
        {
            this.Detalles_Facturas = new HashSet<Detalles_Facturas>();
        }
    
        public int id { get; set; }
        public int id_cliente { get; set; }
        public System.DateTime fecha { get; set; }
        public double descuento { get; set; }
        public double total { get; set; }
        public double subtotal { get; set; }
        public double itbis_total { get; set; }
        public string NFC_comprobante { get; set; }
        public int comprobante_id { get; set; }
        public int usuario_vendedor_id { get; set; }
        public int metodo_pago_id { get; set; }
        public int usuario_cajero_id { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Facturas Facturas1 { get; set; }
        public virtual Facturas Facturas2 { get; set; }
        public virtual Combrobantes Combrobantes { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Metodos_Pagos Metodos_Pagos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalles_Facturas> Detalles_Facturas { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
    }
}
