//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI_V_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordenes_Reservadas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ordenes_Reservadas()
        {
            this.Detalles_Ordenes = new HashSet<Detalles_Ordenes>();
        }
    
        public int id { get; set; }
        public int id_cliente { get; set; }
        public bool estado { get; set; }
        public System.DateTime fecha { get; set; }
        public int id_mesera { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalles_Ordenes> Detalles_Ordenes { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
