//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI_V_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.Detalles_Facturas = new HashSet<Detalles_Facturas>();
            this.Detalles_Ordenes = new HashSet<Detalles_Ordenes>();
        }
    
        public int id { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public int id_categoria { get; set; }
        public decimal precio_normal { get; set; }
        public decimal precio_empleado { get; set; }
        public decimal precio_empresa { get; set; }
        public int id_unidad_medida { get; set; }
        public byte tipo_producto { get; set; }
        public int itbis { get; set; }
        public int cantidad { get; set; }
        public int re_orden { get; set; }
        public bool estado { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        public virtual Unidades_medidas Unidades_medidas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalles_Facturas> Detalles_Facturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalles_Ordenes> Detalles_Ordenes { get; set; }
    }
}
